import { useState, type ReactNode } from "react";
import DemoDialog from "./DemoDialog";
import { useDemoSession } from "./DemoSession";
import { Facts, RecordExplorer } from "./DemoPrimitives";
import { createSalesSamples, salesAmount, salesDate, salesFilters, salesOperation, visibleSalesSamples, type SalesFilter, type SalesSample } from "./demoSales";

type Preview = "summary" | "pickup" | "print" | "accounts" | "cancel" | "modify" | "charge" | "delivery" | "new" | null;

function ActionMenu({ label, children, danger = false }: { label: string; children: ReactNode; danger?: boolean }) {
  return <details className={`sales-action-menu${danger ? " danger" : ""}`}><summary>{label}<span aria-hidden="true">⌄</span></summary><div onClick={(event) => { if (event.target instanceof HTMLElement && event.target.closest("button")) event.currentTarget.parentElement?.removeAttribute("open"); }}>{children}</div></details>;
}

function SampleDocument({ sample, pickup, includeBalances }: { sample: SalesSample; pickup: boolean; includeBalances: boolean }) {
  return <article className="sales-sample-document"><img src="./sistema-ink-icon.png" alt="" /><h3>Atelier Demo</h3><p>{pickup ? "RETIRO EN LOCAL" : "RESUMEN DEL PEDIDO"}</p><strong>{sample.reference}</strong><h4>{sample.customer}</h4><p>{sample.quantity} {sample.unit} · {sample.description}</p><p>Entrega prometida: {salesDate(sample.promised)}</p>{!pickup && <Facts items={[["Total", `NIO ${salesAmount(sample.total)}`], ["Pagado", `NIO ${salesAmount(sample.paid)}`], ["Saldo de este pedido", `NIO ${salesAmount(sample.total - sample.paid)}`], ...(includeBalances ? [["Otros saldos del cliente", "NIO 0.00 · ejemplo"]] as [string, string][] : [])]} />}<small>DATOS FICTICIOS · DEMO<br />No válido como comprobante fiscal</small></article>;
}

export function SalesExample({ onNewExample }: { onNewExample: () => void }) {
  const { state } = useDemoSession();
  const simple = state.mode === "simple";
  const [samples, setSamples] = useState(createSalesSamples);
  const [filter, setFilter] = useState<SalesFilter>("Pendientes");
  const [selectedId, setSelectedId] = useState("PED-DEMO-0203");
  const [query, setQuery] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [documents, setDocuments] = useState(false);
  const [preview, setPreview] = useState<Preview>(null);
  const [includeBalances, setIncludeBalances] = useState(false);
  const [selectedLine, setSelectedLine] = useState<string | null>(null);
  const [productionConfirmed, setProductionConfirmed] = useState(false);
  const [promised, setPromised] = useState("");
  const [status, setStatus] = useState("");
  const visible = visibleSalesSamples(samples, filter, query, from, to);
  const selected = visible.find((sample) => sample.reference === selectedId) ?? visible[0];
  const balance = selected ? selected.total - selected.paid : 0;
  const pending = selected ? selected.quantity - selected.delivered : 0;
  const open = (next: Preview) => { setProductionConfirmed(false); setPreview(next); if (selected) setPromised(selected.promised); };
  const updateSelected = (changes: Partial<SalesSample>, message: string) => {
    if (!selected) return;
    setSamples((current) => current.map((sample) => sample.reference === selected.reference ? { ...sample, ...changes } : sample));
    setPreview(null); setStatus(`${selected.reference} · ${message}`);
  };
  const nextAction = !selected ? "" : pending === 0 ? balance > 0 ? "La entrega está completa; queda pendiente cobrar el saldo." : "Pedido pagado y entregado." : balance > 0 ? simple && state.autoPrepare ? "Cobra el saldo pendiente: al acreditarse, la producción quedaría lista y la entrega continuaría pendiente." : "Cobra el saldo pendiente y continúa con la preparación y la entrega." : selected.ready ? "La producción está lista. Confirma la entrega física al cliente." : "El cobro está completo. Revisa la producción antes de entregar.";

  return <div className="real-module sales-page">
    <header className="sales-page-header" data-guide-target="module-header"><div><h2>{simple ? "Ventas rápidas" : "Ventas y pedidos"}{simple && <span className="sales-mode-badge">MODO SIMPLE</span>}</h2><p>{simple ? "Vende, cobra, imprime y entrega desde un recorrido pensado para una sola persona." : "Captura comercial, fechas y seguimiento operativo en un solo registro."}</p></div><div className="sales-header-actions"><button type="button" aria-pressed={documents} onClick={() => setDocuments(!documents)}>{documents ? "Volver a ventas" : "Documentos emitidos"}</button><button type="button" className="sales-primary" onClick={() => open("new")}><span aria-hidden="true">＋</span> {simple ? "Nueva venta rápida" : "Nueva venta"}</button></div></header>
    {documents ? <section className="sales-documents"><RecordExplorer headers={["Documento", "Pedido", "Tipo", "Estado"]} detailTitle="DOCUMENTO EMITIDO" records={[{ id: "doc", cells: ["DOC-DEMO-0086", "PED-DEMO-0199", "Documento de venta", "Emitido"], title: "Documento de venta · Estudio Prisma", facts: [["Pedido", "PED-DEMO-0199"], ["Total", "NIO 4,600.00"], ["Fecha", "11/09/2026"]], note: "Documento ficticio; sin validación fiscal." }]} /></section> : <div className="sales-workspace">
      <section className="sales-list-pane" aria-label="Lista de pedidos">
        <div className="sales-search" data-guide-target="module-filter"><input type="search" aria-label="Buscar pedido o cliente" placeholder="Buscar pedido o cliente…" value={query} onChange={(event) => { setQuery(event.target.value); setSelectedLine(null); }} /><button type="button" aria-label="Limpiar búsqueda" onClick={() => setQuery("")} disabled={!query}>×</button></div>
        <div className="sales-filter-tabs" role="group" aria-label="Estado de los pedidos" data-guide-target="workspace-tabs">{salesFilters.map((label) => <button type="button" key={label} aria-pressed={filter === label} onClick={() => { setFilter(label); setSelectedLine(null); }}>{label}</button>)}</div>
        <details className="sales-filter-options"><summary>Más filtros y rango de fechas</summary><div><label>Desde<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>Hasta<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><button type="button" onClick={() => { setFrom(""); setTo(""); }}>Limpiar fechas</button></div></details>
        <div className="sales-list-table" data-guide-target="record-list"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Operación</th><th>Saldo</th></tr></thead><tbody>{visible.map((sample) => <tr key={sample.reference} className={`${sample.paid < sample.total ? "unpaid " : ""}${selected?.reference === sample.reference ? "selected" : ""}`} data-guide-target={selected?.reference === sample.reference ? "selected-record" : undefined} onClick={() => { setSelectedId(sample.reference); setSelectedLine(null); setStatus(""); }}><td><button type="button" aria-label={`Ver ${sample.reference}`} aria-pressed={selected?.reference === sample.reference}>{sample.reference}</button><small>{salesDate(sample.date)}</small></td><td>{sample.customer}<small>Cobro: {sample.paid === sample.total ? "Pagado" : sample.paid > 0 ? "Abono" : "Pendiente"}</small></td><td>{salesOperation(sample)}<small>{sample.delivered === sample.quantity ? "Entrega completa" : sample.delivered > 0 ? "Entrega parcial" : "Pendiente"}</small></td><td>{salesAmount(sample.total - sample.paid)}</td></tr>)}</tbody></table>{visible.length === 0 && <p role="status" className="sales-empty">No hay pedidos con estos filtros.</p>}</div>
        <footer className="sales-list-footer"><span>{visible.length} pedido(s)</span><div><button type="button" disabled aria-label="Página anterior">‹</button><span>Página 1 de 1</span><button type="button" disabled aria-label="Página siguiente">›</button></div></footer>
      </section>
      {selected ? <section className="sales-order-pane" aria-label={`Detalle de ${selected.reference}`} data-guide-target="record-detail">
        <header className="sales-order-header"><div><h3>{selected.reference} · {salesOperation(selected)}</h3><p>Origen: pedido directo</p></div><button type="button" className="sales-primary" disabled={pending === 0} onClick={() => open("delivery")}>✓ Registrar entrega</button></header>
        <div className="sales-order-actions"><button type="button" className="sales-primary" onClick={() => open("summary")}>Compartir resumen</button><label><input type="checkbox" checked={includeBalances} onChange={(event) => setIncludeBalances(event.target.checked)} />Incluir otros saldos</label><button type="button" onClick={() => open("accounts")}>Cuentas para pago</button><ActionMenu label="··· Más acciones"><button type="button" onClick={() => open("summary")}>Ver resumen del pedido</button><button type="button" onClick={() => open("pickup")}>Etiqueta de retiro local</button></ActionMenu><ActionMenu label="▤ Imprimir"><button type="button" onClick={() => open("print")}>Resumen del pedido</button><button type="button" onClick={() => open("pickup")}>Retiro local</button></ActionMenu><ActionMenu label="♢ Modificar"><button type="button" onClick={() => open("modify")}>Cambiar fecha de entrega</button></ActionMenu><ActionMenu label="× Cancelar" danger><button type="button" onClick={() => open("cancel")}>Ver cancelación de ejemplo</button></ActionMenu></div>
        <div className="sales-order-scroll">
          <section className="sales-next-action"><div><strong>SIGUIENTE ACCIÓN · {simple ? "MODO SIMPLE" : "POR ÁREAS"}</strong><small>Cobro: {balance > 0 ? `Saldo NIO ${salesAmount(balance)}` : "Pagado"} · {pending > 0 ? "Entrega pendiente" : "Entregado"}</small></div><p>{nextAction}</p><small>{balance > 0 ? "Cobra el saldo desde Caja. Al acreditar la venta, vuelve aquí para imprimir y confirma la entrega física con Entregar ahora." : "El pago y la entrega física se muestran por separado."}</small><div className="sales-next-buttons">{balance > 0 && <button type="button" className="sales-primary" onClick={() => open("charge")}>{simple ? "▣ Cobrar y preparar entrega" : "▣ Cobrar pedido"}</button>}<button type="button" onClick={() => open("pickup")}>◇ Retiro local</button><button type="button" onClick={() => open("summary")}>Compartir resumen</button><button type="button" disabled={pending === 0} onClick={() => open("delivery")}>✓ Entregar ahora</button></div></section>
          <section className="sales-customer"><h3>{selected.customer.toLocaleUpperCase("es")}</h3><p>Contacto de muestra</p><small>RETIRO EN LOCAL</small></section>
          <dl className="sales-totals"><div><dt>TOTAL</dt><dd>NIO {salesAmount(selected.total)}</dd></div><div><dt>PAGADO</dt><dd>NIO {salesAmount(selected.paid)}</dd></div><div><dt>SALDO</dt><dd>NIO {salesAmount(balance)}</dd></div></dl>
          <dl className="sales-dates"><div><dt>Confirmado</dt><dd>{salesDate(selected.date)} 12:21 p. m.</dd></div><div><dt>Entrega prometida</dt><dd>{salesDate(selected.promised)}</dd></div></dl>
          <section className="sales-lines"><h4>Conceptos confirmados</h4><div className="sales-lines-table"><table><thead><tr><th>Elegir</th><th>Descripción</th><th>Acción</th><th>Cant.</th><th>Unidad</th><th>Precio</th><th>Total</th></tr></thead><tbody><tr><td><input type="checkbox" aria-label={`Seleccionar concepto de ${selected.reference}`} checked={selectedLine === selected.reference} onChange={(event) => setSelectedLine(event.target.checked ? selected.reference : null)} /></td><td>{selected.description}</td><td className="sales-line-action">{selected.delivered === selected.quantity ? "ENTREGADO" : selected.ready ? "LISTA PARA ENTREGAR" : balance > 0 ? "PENDIENTE DE COBRO" : "POR HACER"}</td><td>{selected.quantity.toFixed(4)}</td><td>{selected.unit}</td><td>{salesAmount(selected.price)}</td><td>{salesAmount(selected.total)}</td></tr></tbody></table></div></section>
        </div><footer className="sales-order-footer"><span role="status">{status || (selectedLine === selected.reference ? "1 concepto seleccionado" : "")}</span><strong>Total: NIO {salesAmount(selected.total)}</strong></footer>
      </section> : <section className="sales-order-pane sales-empty"><h3>Selecciona un pedido</h3><p>El detalle aparecerá cuando haya resultados.</p></section>}
    </div>}
    {preview && <DemoDialog title={preview === "new" ? simple ? "Nueva venta rápida · Ejemplo" : "Nueva venta · Ejemplo" : `${{ summary: "Resumen", pickup: "Retiro local", print: "Vista previa de impresión", accounts: "Cuentas para pago", cancel: "Cancelación", modify: "Cambiar fecha", charge: "Cobro en Caja", delivery: "Registrar entrega" }[preview]} · ${selected?.reference ?? ""}`} onClose={() => setPreview(null)} footer="Ejemplo abreviado · Datos ficticios · Se restablece al salir de Ventas o recargar">
      {preview === "new" ? <><p>Abre una venta desde la cotización preparada de Café Lumbre en «Seguir un pedido». Podrás confirmar la venta, registrar abonos, verificar transferencias y entregar. Esto reinicia ese recorrido; la captura completa pertenece al sistema instalado.</p><button type="button" className="real-primary-button" onClick={() => { setPreview(null); onNewExample(); }}>Abrir venta de ejemplo</button></> : selected && <>
        {(["summary", "pickup", "print"] as Preview[]).includes(preview) && <><SampleDocument sample={selected} pickup={preview === "pickup"} includeBalances={includeBalances} /><p>Vista previa de muestra. No envía mensajes ni imprime.</p></>}
        {preview === "accounts" && <><h3>Datos de pago de muestra</h3><Facts items={[["Cliente", selected.customer], ["Pedido", selected.reference], ["Saldo", `NIO ${salesAmount(balance)}`], ["Banco", "Banco Demo"], ["Cuenta", "DEMO · No utilizable para pagos"]]} /><p>Las cuentas reales de la empresa no se incluyen en esta demostración.</p></>}
        {preview === "cancel" && <><Facts items={[["Pedido", selected.reference], ["Cobrado", `NIO ${salesAmount(selected.paid)}`], ["Entregado", `${selected.delivered} de ${selected.quantity} ${selected.unit}`]]} /><p>En el sistema se revisan el motivo, los conceptos y las devoluciones que correspondan antes de cancelar. Esta vista no reproduce esos pasos ni modifica el pedido de muestra.</p></>}
        {preview === "modify" && <form className="faithful-form" onSubmit={(event) => { event.preventDefault(); updateSelected({ promised }, "Fecha de entrega actualizada en el ejemplo."); }}><label>Entrega prometida<input type="date" required value={promised} onChange={(event) => setPromised(event.target.value)} /></label><button type="submit" className="real-primary-button">Guardar fecha de ejemplo</button></form>}
        {preview === "charge" && <><h3>Mostrador DEMO · Caja abierta</h3><Facts items={[["Cliente", selected.customer], ["Total", `NIO ${salesAmount(selected.total)}`], ["Pagado", `NIO ${salesAmount(selected.paid)}`], ["Saldo a cobrar", `NIO ${salesAmount(balance)}`], ["Método del ejemplo", "Efectivo"]]} /><p>Este paso abreviado muestra el pago completo en efectivo. «Seguir un pedido» permite practicar abonos, transferencias y recibos.</p><button type="button" className="real-primary-button" onClick={() => updateSelected({ paid: selected.total, ready: selected.ready || (simple && state.autoPrepare) }, "Cobro ficticio aplicado. La entrega física conserva su estado.")}>Confirmar cobro de ejemplo</button></>}
        {preview === "delivery" && <><Facts items={[["Cliente", selected.customer], ["Cantidad del pedido", `${selected.quantity} ${selected.unit}`], ["Entregado", `${selected.delivered} ${selected.unit}`], ["Pendiente de entregar", `${pending} ${selected.unit}`], ["Saldo que se conserva", `NIO ${salesAmount(balance)}`]]} />{!selected.ready && <label className="scenario-production-confirmation"><input type="checkbox" checked={productionConfirmed} onChange={(event) => setProductionConfirmed(event.target.checked)} />Confirmo que toda la línea está terminada y lista para entregar.</label>}<p>El ejemplo entrega toda la cantidad pendiente. La entrega no registra un cobro.</p><button type="button" className="real-primary-button" disabled={!selected.ready && !productionConfirmed} onClick={() => updateSelected({ delivered: selected.quantity, ready: true }, "Entrega ficticia registrada; el saldo no cambia.")}>Confirmar entrega de ejemplo</button></>}
      </>}
    </DemoDialog>}
  </div>;
}
