import { useState } from "react";
import { useDemoSession } from "./DemoSession";
import { DEMO_ORDER, scenarioSummary } from "./demoScenario";
import { DemoPage, Facts, Metrics, PreviewButton, demoMoney } from "./DemoPrimitives";
import DemoDialog, { DocumentExample } from "./DemoDialog";
import type { GuideModuleId } from "./InteractiveGuide";

export const scenarioModules = new Set<GuideModuleId>(["panel", "cotizaciones", "ventas", "caja", "produccion", "entregas", "inventario", "finanzas"]);

export default function ScenarioModule({ active, onNavigate }: { active: GuideModuleId; onNavigate: (id: GuideModuleId) => void }) {
  const { state, dispatch } = useDemoSession();
  const summary = scenarioSummary(state);
  const [confirmDelivery, setConfirmDelivery] = useState(false);
  const [amount, setAmount] = useState("");
  const [quantity, setQuantity] = useState("");
  const [method, setMethod] = useState<"cash" | "transfer">("cash");
  const [error, setError] = useState("");
  const [preview, setPreview] = useState<"receipt" | "label" | null>(null);
  const payable = Math.round((summary.balance - state.pendingTransfer) * 100) / 100;
  const productionLabel = state.production === "pending" ? "Por hacer" : state.production === "active" ? "En proceso" : "Finalizada";
  const go = (id: GuideModuleId, label: string) => <button type="button" className="real-primary-button" onClick={() => onNavigate(id)}>{label}</button>;
  const deliver = <button type="button" className="real-primary-button" onClick={() => state.mode === "simple" ? setConfirmDelivery(true) : onNavigate("entregas")}>Entregar ahora</button>;
  const titles: Partial<Record<GuideModuleId, string>> = { panel: "Un pedido, de principio a fin", cotizaciones: "Cotizaciones", ventas: state.mode === "simple" ? "Ventas rápidas" : "Ventas y pedidos", caja: state.mode === "simple" ? "Cobro rápido" : "Caja", produccion: "Producción", entregas: "Entregas", inventario: "Inventario", finanzas: "Cuentas por cobrar" };
  return <DemoPage title={titles[active] ?? "Pedido de ejemplo"} description={`${DEMO_ORDER.reference} · ${DEMO_ORDER.customer} · ${DEMO_ORDER.quantity} camisetas · Simulación en memoria`}>
    <div className="scenario-context"><span>EJEMPLO INTERACTIVO</span><p>Prueba el flujo. Solo cambia este pedido ficticio; puedes reiniciarlo en cualquier momento.</p></div>
    <Metrics items={[["Total", demoMoney(DEMO_ORDER.total)], ["Pagado", demoMoney(state.paid)], ["Saldo", demoMoney(summary.balance)], ["Entrega física", `${state.delivered} / ${DEMO_ORDER.quantity}`]]} />
    <div className="faithful-split scenario-layout"><section className="internal-card scenario-task" data-guide-target="record-list">
      {active === "panel" && <><h3>{summary.complete ? "Pedido cobrado y entregado" : "Conserva el contexto en cada paso"}</h3><p>Aprueba la cotización, crea el pedido, registra un abono o una transferencia, prepara el trabajo y confirma la entrega.</p><div className="scenario-route">{["Cotización", "Venta", "Cobro", "Producción", "Entrega"].map((name, index) => <span key={name}><b>{index + 1}</b>{name}</span>)}</div>{go(state.quote === "draft" ? "cotizaciones" : "ventas", summary.complete ? "Revisar pedido" : "Continuar ejemplo")}<p>Este es un recorrido posible: el sistema también admite ventas directas, crédito, entregas parciales e incidencias.</p></>}
      {active === "cotizaciones" && <><h3>{DEMO_ORDER.quote}</h3><Facts items={[["Cliente", DEMO_ORDER.customer], ["Concepto", DEMO_ORDER.product], ["Cantidad", DEMO_ORDER.quantity], ["Precio unitario", demoMoney(DEMO_ORDER.unitPrice)], ["Estado", state.quote === "draft" ? "Borrador" : state.quote === "approved" ? "Aprobada" : "Convertida a pedido"]]} />
        <div className="faithful-actions"><button type="button" className="real-primary-button" disabled={state.quote !== "draft"} onClick={() => dispatch({ type: "approve" })}>Aprobar cotización</button><button type="button" className="real-primary-button" disabled={state.quote !== "approved"} onClick={() => { dispatch({ type: "convert" }); onNavigate("ventas"); }}>Convertir a pedido</button></div></>}
      {active === "ventas" && <><h3>{summary.ordered ? DEMO_ORDER.reference : "La cotización todavía no es un pedido"}</h3>{summary.ordered ? <><Facts items={[["Cliente", DEMO_ORDER.customer], ["Pago", summary.paymentLabel], ["Producción", productionLabel], ["Entrega", summary.deliveryLabel]]} /><div className="faithful-actions">{summary.balance > 0 && go("caja", "Cobrar y preparar entrega")}{state.production !== "finished" && go("produccion", "Revisar producción")}{state.production === "finished" && summary.pendingDelivery > 0 && deliver}<PreviewButton onClick={() => setPreview("label")}>Vista previa de etiqueta</PreviewButton></div><p>Pagado no significa entregado. El pedido conserva cantidades pendientes hasta confirmar la entrega física.</p></> : go("cotizaciones", "Revisar cotización")}</>}
      {active === "caja" && <><h3>Mostrador DEMO · Caja abierta</h3>{summary.ordered ? <><div className="faithful-actions" role="group" aria-label="Forma de pago del ejemplo"><button type="button" aria-pressed={method === "cash"} onClick={() => { setMethod("cash"); setError(""); }}>Efectivo</button><button type="button" aria-pressed={method === "transfer"} onClick={() => { setMethod("transfer"); setError(""); }}>Transferencia</button></div>
        <form className="faithful-form" onSubmit={(event) => { event.preventDefault(); const value = Number(amount || payable); if (!Number.isFinite(value) || value <= 0 || value > payable) { setError("El importe debe ser positivo y no superar el saldo disponible para aplicar."); return; } dispatch({ type: "pay", amount: value, method }); setAmount(""); setError(""); }}>
          <label>Importe a aplicar (NIO)<input aria-label="Importe del cobro de ejemplo" type="number" required min="0.01" max={payable || 0.01} step="0.01" value={amount || (payable > 0 ? payable : "")} onChange={(e) => setAmount(e.target.value)} disabled={payable <= 0} /></label>
          <p>{method === "transfer" && state.transferPolicy === "verify" ? "Política del ejemplo: aplicar después de verificar. El saldo no cambia mientras esté pendiente." : "El importe se aplica al confirmar este cobro ficticio."}</p>
          <button className="real-primary-button" type="submit" disabled={payable <= 0}>{method === "transfer" && state.transferPolicy === "verify" ? "Registrar para verificar" : "Registrar cobro de ejemplo"}</button>{error && <p role="alert">{error}</p>}
        </form>
        {state.pendingTransfer > 0 && <div className="scenario-pending"><strong>Por verificar: {demoMoney(state.pendingTransfer)}</strong><button type="button" className="real-primary-button" onClick={() => dispatch({ type: "verify" })}>Verificar transferencia de ejemplo</button></div>}
        {state.paid > 0 && <PreviewButton onClick={() => setPreview("receipt")}>Ver comprobante de ejemplo</PreviewButton>}
        {summary.balance === 0 && <div className="scenario-pending"><strong>{summary.deliveryLabel}</strong>{summary.pendingDelivery > 0 && (state.production === "finished" ? deliver : go("produccion", "Revisar producción"))}</div>}
      </> : go("cotizaciones", "Crear el pedido primero")}</>}
      {active === "produccion" && <><h3>Estampado frontal</h3><Facts items={[["Pedido", DEMO_ORDER.reference], ["Cantidad", "12 unidades"], ["Estado", productionLabel], ["Técnica", "Estampado textil"], ["Control", "Pedido · Acción · Materiales · Tiempo"]]} /><div className="faithful-actions"><button type="button" className="real-primary-button" disabled={!summary.ordered || state.production !== "pending"} onClick={() => dispatch({ type: "start" })}>Iniciar</button><button type="button" className="real-primary-button" disabled={state.production !== "active"} onClick={() => dispatch({ type: "finish" })}>Finalizar</button>{state.production === "finished" && go("entregas", "Revisar cantidades por entregar")}</div>
        <p>{state.mode === "simple" && state.autoPrepare ? "En Simple, cancelar el saldo también puede dejar la producción lista cuando la empresa activa esa política." : "Por áreas mantiene las confirmaciones de trabajo separadas del cobro."}</p><p>El ejemplo omite cronometraje y consumos reales. Calidad se utiliza si existe una incidencia; no exige una aprobación universal.</p></>}
      {active === "entregas" && <><h3>Cantidades del pedido</h3><Facts items={[["Solicitado", DEMO_ORDER.quantity], ["Entregado", state.delivered], ["Pendiente", summary.pendingDelivery], ["Producción", productionLabel]]} />
        <form className="faithful-form" onSubmit={(event) => { event.preventDefault(); const value = state.mode === "simple" ? summary.pendingDelivery : Number(quantity || summary.pendingDelivery); if (!Number.isInteger(value) || value <= 0 || value > summary.pendingDelivery) { setError("Indica una cantidad entera que no supere lo pendiente."); return; } dispatch({ type: "deliver", quantity: value }); setQuantity(""); setError(""); }}>
          {state.mode === "areas" && <label>Unidades a entregar<input type="number" min="1" step="1" max={summary.pendingDelivery || 1} value={quantity || (summary.pendingDelivery || "")} onChange={(e) => setQuantity(e.target.value)} disabled={!summary.pendingDelivery} /></label>}
          <p>{state.mode === "simple" ? "Simple propone entregar todo lo pendiente en una sola confirmación." : "Por áreas permite indicar una entrega parcial y conservar el resto pendiente."}</p>
          <button className="real-primary-button" type="submit" disabled={!summary.ordered || state.production !== "finished" || summary.pendingDelivery === 0}>{state.mode === "simple" ? "Confirmar entrega de ejemplo" : "Registrar entrega de ejemplo"}</button>{error && <p role="alert">{error}</p>}
        </form>{state.production !== "finished" && <p>Este recorrido prepara las 12 unidades antes de registrar su entrega.</p>}{go("inventario", "Ver efecto en inventario")}
      </>}
      {active === "inventario" && <><h3>Camiseta blanca · Almacén principal</h3><Metrics items={[["Físico", summary.physical], ["Reservado", summary.reserved], ["Disponible", summary.available]]} /><Facts items={[["Existencia inicial del ejemplo", "36 unidades"], ["Cantidad del pedido", summary.ordered ? "12 unidades" : "Sin pedido todavía"], ["Salidas por entrega", `${state.delivered} unidades`]]} /><p>El cobro no produce una entrega. Este artículo del ejemplo sale físicamente cuando se registra la entrega; lo pendiente conserva su reserva.</p>{go("ventas", "Volver al pedido")}</>}
      {active === "finanzas" && (summary.ordered ? <><h3>Saldo de {DEMO_ORDER.customer}</h3><Facts items={[["Referencia", DEMO_ORDER.reference], ["Importe", demoMoney(DEMO_ORDER.total)], ["Aplicado", demoMoney(state.paid)], ["Por verificar", demoMoney(state.pendingTransfer)], ["Saldo pendiente", demoMoney(summary.balance)]]} /><p>La transferencia pendiente no reduce el saldo hasta que se aplica. Los mismos importes aparecen en Ventas y Caja.</p>{go("caja", "Revisar cobro")}</> : <><h3>Sin cuenta por cobrar</h3><p>La cotización todavía no crea una deuda del cliente. Primero conviértela en pedido.</p>{go("cotizaciones", "Revisar cotización")}</>)}
    </section><aside className="detail-pane faithful-detail" data-guide-target="record-detail"><small>TRAZABILIDAD DEL EJEMPLO</small><h3>{DEMO_ORDER.customer}</h3><Facts items={[["Cotización", DEMO_ORDER.quote], ["Pedido", summary.ordered ? DEMO_ORDER.reference : "Pendiente de convertir"], ["Producción", productionLabel], ["Pago", summary.paymentLabel], ["Entrega", summary.deliveryLabel]]} />
      <ol className="scenario-history">{state.events.map((event, index) => <li key={`${index}-${event}`}>{event}</li>)}</ol><p className="scenario-status" role="status">{state.events[state.events.length - 1]}</p>
      {summary.complete && <strong className="scenario-complete">Ciclo completado: cobrado y entregado.</strong>}
    </aside></div>
    {confirmDelivery && <DemoDialog title="Confirmar entrega de ejemplo" onClose={() => setConfirmDelivery(false)}><h3>{DEMO_ORDER.reference} · {DEMO_ORDER.customer}</h3><p>Se entregarán las {summary.pendingDelivery} unidades pendientes. La existencia física disminuirá en esa cantidad; el saldo financiero se conserva.</p><div className="faithful-actions"><button type="button" className="real-primary-button" onClick={() => { dispatch({ type: "deliver", quantity: summary.pendingDelivery }); setConfirmDelivery(false); }}>Confirmar entrega de ejemplo</button><PreviewButton onClick={() => setConfirmDelivery(false)}>Volver sin entregar</PreviewButton></div></DemoDialog>}
    {preview && <DemoDialog title={`Vista previa del ${preview === "label" ? "envío" : "cobro"} de ejemplo`} onClose={() => setPreview(null)}><DocumentExample kind={preview} paid={state.paid} />{preview === "receipt" && <p>Resumen ilustrativo acumulado; el producto emite recibos individuales inmutables por movimiento.</p>}</DemoDialog>}
  </DemoPage>;
}
